In [ ]:
#Numpy
#Numpy is what is happening in the background Pandas
#Numpy is built on C++

: 

In [ ]:
# Numpy is a lot more efficent than Python
# 50x - 100x faster
# Arrays, C++ Arrays = Contiguous memory, optimized searches
# Lists in python can contain multiple types, and are not "Arrays"
# Numpy arrays are all one one data type, and stored in an nd-array


In [1]:
import numpy as np

print(np.__version__)

2.0.0


In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [7]:
#Dimensions - n-dimensional array

#0-3D arrays

#0D Array aka scalar
zero_arr = np.array(42)

#1D Array AKA Array
one_arr = np.array([1,2,3,4,5])

#2D Array AKA Matrix
two_arr = np.array([[1,2,3], [4,5,6]])
print(two_arr)

#3D Array AKA Tensor

three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
print(three_arr)
print(zero_arr.ndim, one_arr.ndim, two_arr.ndim, three_arr.ndim)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
0 1 2 3


In [10]:
#indexing into our nd arrays

#Python indexing - Do not do this 
print(two_arr[0][1])

#numpy indexing
print(two_arr[0,1])

print(three_arr[0,1,2])

2
2
6


In [12]:
# Numpy arrays are a single datatype 
# Numpy has its own datatype 
# i - integers up to int64
# b - boolean
# u - unsigned ints
# f - float -float 128
# c - complex
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode strings
# v - void type - fixed chunk of memory that is reserved

print(arr.dtype)

arr = np.array([1,2,3,4,5], dtype='f')
print(arr.dtype)

int64
float32


In [15]:
# checking our matrixes shape 

print(arr.shape)
print(two_arr.shape) # 2 rows, 3 columns

(5,)
(2, 3)


In [16]:
# Reshape arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
new_arr = arr.reshape(4,3)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
# If we do not know our full dimensions we can substitute an -1

new_arr = arr.reshape(2,2,-1)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
# To flatten our arrays
arr = new_arr.reshape(-1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
# Iterating thru arrays
print(three_arr)
for x in np.nditer(three_arr):
    print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [24]:
# joining arrays
# join based on axis
# axis = 0 is based on rows, axis = 1 is based on columns
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
#join based off of rows
big_arr = np.concatenate((arr1,arr2), axis=0)
print(big_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
#join based off of columns
diff_big_arr = np.concatenate((arr1,arr2), axis=1)
print(diff_big_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
# Stacking
# Stack(), hstack(), dstack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
print(arr) 
arr = np.hstack((arr1, arr2))
print(arr)
arr = np.dstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [29]:
#split array into n number of parts
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.array_split(arr, 3)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5])]


In [31]:
#searching our arrays is done with the where() method

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [32]:
#searchsorted() array must already be sorted
arr = np.array([1, 2 ,3 ,4 , 5, 6])
x = np.searchsorted(arr, 6)
print(x)

5


In [33]:
#sorting arrays
#can still use python sort() method 
#np.sort()

arr = np.array([[5,2,1],[6,3,9]])
print(np.sort(arr))

[[1 2 5]
 [3 6 9]]


In [34]:
# filtering our arrays
#filter based off of a conditon 
# Or we can use a boolean array
arr = np.array([40, 20, 32, 23334])
x = [False, True, False, False]
filtered_arr = arr[x]
print(filtered_arr)

[20]


In [40]:
# copies vs views
# when we work with big data 
# 4 GB file -> 8 GB
# 11 GB file -> 22 GB
# Use a view

arr = np.array([1,2,3,4])
print(arr)
view = arr.view()
copy = arr.copy()
arr[0] = 15
print(view)
print(copy)

print(view.base)
print(copy.base)

[1 2 3 4]
[15  2  3  4]
[1 2 3 4]
[15  2  3  4]
None


In [41]:
import time

In [42]:
# Use python list
start = time.time()
list = [i for i in range(1_000_000)]
squared = [x**2 for x in list]
stop = time.time()
print(stop-start)

0.8107006549835205


In [43]:
#Using numpy 
start = time.time()
arr = np.arange(1_000_000)
squared = arr**2
stop = time.time()
print(stop-start)

0.04791450500488281


: 